# Generated by Django 4.2 on 2023-05-02 23:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/user.png', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
