# Generated by Django 4.2 on 2023-05-02 22:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_author_articleseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.png', max_length=255, upload_to=core.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.png', max_length=255, upload_to=core.models.ArticleSeries.image_upload_to),
        ),
    ]
