# Generated by Django 4.2 on 2023-05-08 01:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_image_articleseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/efa239eb63acab82204c4ce60702c469.jpg', max_length=255, upload_to=core.models.Article.image_upload_to),
        ),
    ]
